language: node_js
node_js:
  - '12'

notifications:
  email:
    on_success: never
    on_failure: always

script: yarn build

deploy:
  provider: npm
  email: npm@jupiterone.io
  api_key:
    secure: "ZRzv6dnk60CFzWzeWyD2t+3VcPNOyZ/ELqjpARjE/VkJy4e4u7wuPSDmS3Dslh2nigZSnRBCO5caPiB8Dz3jTE7MxaF7cyl0AvjMzltKR+QD5t4kN3b7wpaiaRTRjdG0MtV4brIKwx8fpItHLdtMpJBBiqYbFy0qLdx8qy1/b1E/a4EBIbN1g9p9w0GI72qWfjPTp5kgQYQ7cTpn6tkwKSJK7hnG/+11RyV9fK75uURw6fLuhMICf4PCnlo5wvdQlrESieyA/THygu4M5vyhMHFpqRd/EkY29XO6qR2uUCy1TUnNUFAy4lkovMBwq4gxSl+FJ32Xw9T22qQ/dbUehH5q3oW/HoSnqCozqXhateZic3brzHHm9w/rkSPNbu3t2w9H2oQVPCIrbgerDSXmBYJ0OYs7p+zMXUFCRXzKQq1ytIzeNOYJSlU2xzXG/S5XxNh+A5x5EbAlQINqzj37e1oYvoHkkuPAJYanRlHzzybVymEcMH/+2COzrw5MP66xQ7rB2Ri4x2nDdQRDX23bdUo2ZaKZ0bMG0fpI5WefVgtGWfBxnvVi0DUWb3RBRfjH/dr8hcODCcyHXyZmiF1oQPXilc7RP1J3w6tAniJV73vt9VZxU689K6LeQi2HhFVlEUCKc/ZGrPADUklGLBOAvw7ZV5vjO3PqqSRQcRZOMsA="
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: JupiterOne/graph-knowbe4
    node: '12'
